### ISSUE TITLE
[TASKS] To do by deadline

### ISSUE THREAD

**Issue by itszp** [CS2103-AY1819S2-W14-2/main#114]
## Tasks to Complete
Here are the tasks to complete after our last meeting. **Please tick when completed.**

**Kay Heen**
- [x] Architecture Component
- [x] Sequence Component 
- [x] Individual Features Implementation

**Si Mun**
- [x] Logic Component Sequence Diagram (to work with Randy)
- [x] Storage Component
- [x] Individual Features Implementation

**Randy**
- [x] Logic OODM (to work with Si Mun)
- [x] Use cases appendix
- [x] Individual Features Implementation

**Zack**
- [x] Model Component
- [x] Use cases appendix
- [x] Individual Features Implementation

**Addison**
- [x] UI Component
- [x] Individual Features Implementation

**Comment by itszp** [comment]
Complete. Good job everyone!
